# Generated by Django 5.1.7 on 2025-04-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Dueño al Reservar'),
        ),
    ]
