# Generated by Django 5.1.7 on 2025-04-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0003_alter_booking_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='booking',
            name='staff_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Internas del Staff'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='comportamiento_notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas sobre la Mascota'),
        ),
    ]
