# Generated by Django 5.1.7 on 2025-04-23 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0005_service_alter_booking_options_booking_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='daycare.service', verbose_name='Servicio'),
            preserve_default=False,
        ),
    ]
