"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l@=usypc=%%vm=ok9rnkdt6y#uu)nyk7078069y&(hi8d38c*#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.1.38']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'daycare',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # <--- Asegúrate de que esta línea esté así
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Directorios adicionales donde Django buscará archivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), # <--- Asegúrate de que esta línea esté así
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL = '/daycare/'
LOGIN_URL = '/accounts/login/' # URL a la que se redirige a usuarios no autenticados que intentan acceder a páginas restringidas
LOGIN_REDIRECT_URL_STAFF = '/daycare/staff/calendar/' # Redirigir staff a la lista de reservas

LOGOUT_REDIRECT_URL = '/' # Redirige a la página de inicio después de cerrar sesión

# Opcionalmente, si necesitas una página de login específica (Django ya proporciona una por defecto)
# LOGIN_URL = '/accounts/login/'

# Configuración para archivos media (subidos por usuarios)
MEDIA_URL = '/media/' # URL pública para acceder a los archivos media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Directorio físico donde se guardarán los archivos

# Configuración de Email para el restablecimiento de contraseña (y otros envíos)
# --- Usando Backend de Consola para Desarrollo ---
# Esto imprime los emails en la terminal donde corres runserver.
# Es la forma RECOMENDADA para desarrollo cuando el SMTP real falla o no es necesario.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # <--- Usa este backend para desarrollo

# --- Tu configuración SMTP (comentada o mantenida aparte para referencia) ---
# Cuando prepares para producción, deberás usar un backend SMTP real y configurar
# estos valores correctamente para tu servicio de email de producción.
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # Backend SMTP real (para producción)
# EMAIL_HOST = 'smtp.gmail.com' # Ejemplo de configuración SMTP
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_HOST_USER = 'tu_correo_de_envio@gmail.com'
# EMAIL_HOST_PASSWORD = 'tu_contraseña_o_contraseña_de_aplicacion'
# DEFAULT_FROM_EMAIL = 'Guardería Canina <no-responder@tu-dominio.com>'