# Generated by Django 5.2 on 2025-04-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tiempo_preparacion', models.CharField(blank=True, max_length=50)),
                ('tiempo_coccion', models.CharField(blank=True, max_length=50)),
                ('ingredientes', models.TextField()),
                ('instrucciones', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
